import type { Player, Evidence, Recommendation } from "@/lib/types";

const now = new Date();
const hours4 = new Date(now.getTime() + 4 * 60 * 60 * 1000);

export interface ExtendedPlayer extends Player {
  adp: number;
  tier: number;
  bye: number;
  projectedPpg: number;
  floorPpg: number;
  ceilingPpg: number;
  targetShare: number;
  snapShare: number;
  redzoneTouchShare: number;
  matchupRank: string; // e.g. "2nd vs WR" (Good) or "28th vs WR" (Tough)
  matchupDifficulty: "easy" | "neutral" | "hard";
  injuryRiskScore: number; // 0 (healthy) to 100 (high risk)
  evidenceCount: number;
}

export const demoPlayers: ExtendedPlayer[] = [
  {
    id: "p-101",
    sleeperId: "sl-101",
    nflverseId: "nfl-jj-18",
    fullName: "Justin Jefferson",
    position: "WR",
    team: "MIN",
    byeWeek: 6,
    bye: 6,
    status: "Active",
    adp: 4.2,
    tier: 1,
    projectedPpg: 19.8,
    floorPpg: 14.2,
    ceilingPpg: 28.5,
    targetShare: 29.4,
    snapShare: 94.2,
    redzoneTouchShare: 31.0,
    matchupRank: "#2 vs Secondary",
    matchupDifficulty: "easy",
    injuryRiskScore: 12,
    evidenceCount: 6,
  },
  {
    id: "p-102",
    sleeperId: "sl-102",
    nflverseId: "nfl-cd-88",
    fullName: "CeeDee Lamb",
    position: "WR",
    team: "DAL",
    byeWeek: 7,
    bye: 7,
    status: "Active",
    adp: 5.1,
    tier: 1,
    projectedPpg: 19.4,
    floorPpg: 13.8,
    ceilingPpg: 27.2,
    targetShare: 28.8,
    snapShare: 92.0,
    redzoneTouchShare: 28.5,
    matchupRank: "#5 vs Secondary",
    matchupDifficulty: "easy",
    injuryRiskScore: 15,
    evidenceCount: 5,
  },
  {
    id: "p-103",
    sleeperId: "sl-103",
    nflverseId: "nfl-cmc-23",
    fullName: "Christian McCaffrey",
    position: "RB",
    team: "SF",
    byeWeek: 9,
    bye: 9,
    status: "Questionable",
    adp: 1.8,
    tier: 1,
    projectedPpg: 21.5,
    floorPpg: 11.0,
    ceilingPpg: 32.0,
    targetShare: 18.5,
    snapShare: 82.5,
    redzoneTouchShare: 44.0,
    matchupRank: "#12 vs Run Def",
    matchupDifficulty: "neutral",
    injuryRiskScore: 48,
    evidenceCount: 8,
  },
  {
    id: "p-104",
    sleeperId: "sl-104",
    nflverseId: "nfl-ja-17",
    fullName: "Josh Allen",
    position: "QB",
    team: "BUF",
    byeWeek: 12,
    bye: 12,
    status: "Active",
    adp: 22.4,
    tier: 1,
    projectedPpg: 22.8,
    floorPpg: 16.5,
    ceilingPpg: 34.0,
    targetShare: 0,
    snapShare: 100.0,
    redzoneTouchShare: 26.0,
    matchupRank: "#3 vs Pass Def",
    matchupDifficulty: "easy",
    injuryRiskScore: 10,
    evidenceCount: 4,
  },
  {
    id: "p-105",
    sleeperId: "sl-105",
    nflverseId: "nfl-br-07",
    fullName: "Bijan Robinson",
    position: "RB",
    team: "ATL",
    byeWeek: 12,
    bye: 12,
    status: "Active",
    adp: 6.8,
    tier: 1,
    projectedPpg: 18.2,
    floorPpg: 12.5,
    ceilingPpg: 26.4,
    targetShare: 15.2,
    snapShare: 78.4,
    redzoneTouchShare: 38.0,
    matchupRank: "#8 vs Run Def",
    matchupDifficulty: "easy",
    injuryRiskScore: 8,
    evidenceCount: 4,
  },
  {
    id: "p-106",
    sleeperId: "sl-106",
    nflverseId: "nfl-il-80",
    fullName: "Isaiah Likely",
    position: "TE",
    team: "BAL",
    byeWeek: 14,
    bye: 14,
    status: "Active",
    adp: 114.5,
    tier: 3,
    projectedPpg: 13.6,
    floorPpg: 7.2,
    ceilingPpg: 22.8,
    targetShare: 21.0,
    snapShare: 74.0,
    redzoneTouchShare: 24.0,
    matchupRank: "#1 vs TE Coverage",
    matchupDifficulty: "easy",
    injuryRiskScore: 14,
    evidenceCount: 7,
  },
  {
    id: "p-107",
    sleeperId: "sl-107",
    nflverseId: "nfl-mhj-18",
    fullName: "Marvin Harrison Jr.",
    position: "WR",
    team: "ARI",
    byeWeek: 11,
    bye: 11,
    status: "Active",
    adp: 18.5,
    tier: 2,
    projectedPpg: 16.4,
    floorPpg: 9.5,
    ceilingPpg: 25.0,
    targetShare: 26.2,
    snapShare: 91.5,
    redzoneTouchShare: 22.0,
    matchupRank: "#18 vs Pass Def",
    matchupDifficulty: "neutral",
    injuryRiskScore: 16,
    evidenceCount: 5,
  },
  {
    id: "p-108",
    sleeperId: "sl-108",
    nflverseId: "nfl-sp-26",
    fullName: "Samaje Perine",
    position: "RB",
    team: "KC",
    byeWeek: 6,
    bye: 6,
    status: "Active",
    adp: 154.0,
    tier: 5,
    projectedPpg: 6.8,
    floorPpg: 3.0,
    ceilingPpg: 11.5,
    targetShare: 6.4,
    snapShare: 32.0,
    redzoneTouchShare: 8.0,
    matchupRank: "#24 vs Run Def",
    matchupDifficulty: "hard",
    injuryRiskScore: 22,
    evidenceCount: 3,
  },
  {
    id: "p-109",
    sleeperId: "sl-109",
    nflverseId: "nfl-btj-82",
    fullName: "Brian Thomas Jr.",
    position: "WR",
    team: "JAX",
    byeWeek: 12,
    bye: 12,
    status: "Active",
    adp: 48.2,
    tier: 3,
    projectedPpg: 14.8,
    floorPpg: 7.8,
    ceilingPpg: 24.2,
    targetShare: 23.5,
    snapShare: 86.0,
    redzoneTouchShare: 19.5,
    matchupRank: "#4 vs Pass Def",
    matchupDifficulty: "easy",
    injuryRiskScore: 12,
    evidenceCount: 6,
  },
];

export const demoEvidence: Evidence[] = [
  {
    id: "ev-1",
    playerId: "p-106",
    type: "usage",
    source: "nflverse_play_by_play",
    sourceUrl: "https://nflverse.org/data/2026",
    observedAt: new Date(now.getTime() - 2 * 3600000).toISOString(),
    publishedAt: new Date(now.getTime() - 3 * 3600000).toISOString(),
    confidence: 0.94,
    summary: "Isaiah Likely ran routes on 78% of dropbacks in 2-TE sets, leading all TEs in Week 1 target rate per route run (31%).",
    fingerprint: "usage-likely-w1-target-surge",
  },
  {
    id: "ev-2",
    playerId: "p-103",
    type: "injury",
    source: "sleeper_injury_feed",
    sourceUrl: "https://sleeper.app/players/cmc",
    observedAt: new Date(now.getTime() - 1 * 3600000).toISOString(),
    publishedAt: new Date(now.getTime() - 1.5 * 3600000).toISOString(),
    confidence: 0.88,
    summary: "Christian McCaffrey practiced in limited capacity (Achilles/Calf). Role certainty lowered by 15%.",
    fingerprint: "injury-cmc-limited-practice",
  },
  {
    id: "ev-3",
    playerId: "p-101",
    type: "projection",
    source: "war_room_engine_v1",
    observedAt: now.toISOString(),
    confidence: 0.96,
    summary: "Justin Jefferson projection boosted +1.8 PPG due to secondary matchup efficiency rating #2 overall.",
    fingerprint: "proj-jj-matchup-boost",
  },
  {
    id: "ev-4",
    playerId: "p-109",
    type: "depth_chart",
    source: "nflverse_depth_charts",
    observedAt: new Date(now.getTime() - 5 * 3600000).toISOString(),
    confidence: 0.91,
    summary: "Brian Thomas Jr. promoted to primary X-receiver in 2-WR base packages.",
    fingerprint: "depth-btj-x-receiver",
  },
];

export const demoRecommendations: Recommendation[] = [
  {
    id: "rec-today-1",
    kind: "add",
    subjectPlayerId: "p-106",
    score: 92,
    confidence: 94,
    headline: "Add Isaiah Likely before waiver cutoff",
    reasonCodes: ["TARGET_SHARE_SURGE", "TE_SCARCITY_EDGE", "HIGH_ROS_VALUE"],
    evidenceIds: ["ev-1"],
    computedAt: now.toISOString(),
    freshUntil: hours4.toISOString(),
    engineVersion: "war-v0.1.0",
  },
  {
    id: "rec-today-2",
    kind: "start",
    subjectPlayerId: "p-101",
    alternativePlayerId: "p-107",
    score: 89,
    confidence: 91,
    headline: "Start Justin Jefferson over Marvin Harrison Jr.",
    reasonCodes: ["MATCHUP_ADVANTAGE", "FLOOR_CEILING_EDGE", "USAGE_DOMINANCE"],
    evidenceIds: ["ev-3"],
    computedAt: now.toISOString(),
    freshUntil: hours4.toISOString(),
    engineVersion: "war-v0.1.0",
  },
  {
    id: "rec-today-3",
    kind: "watch",
    subjectPlayerId: "p-103",
    score: 74,
    confidence: 78,
    headline: "Watch McCaffrey injury participation before Sunday lock",
    reasonCodes: ["LIMITED_PRACTICE", "HIGH_VOLATILITY", "HANDOFF_BACKUP_RISK"],
    evidenceIds: ["ev-2"],
    computedAt: now.toISOString(),
    freshUntil: hours4.toISOString(),
    engineVersion: "war-v0.1.0",
  },
];

export const demoWhatChangedToday = [
  {
    id: "diff-1",
    time: "2 hours ago",
    type: "USAGE_SURGE",
    player: "Isaiah Likely (TE · BAL)",
    metric: "Route Share +24%",
    delta: "+3.8 PPG Projection",
    source: "nflverse play-by-play telemetry",
    significance: "high",
  },
  {
    id: "diff-2",
    time: "4 hours ago",
    type: "INJURY_VOLATILITY",
    player: "Christian McCaffrey (RB · SF)",
    metric: "Practice: Limited (Achilles)",
    delta: "Floor lowered to 11.0 pts",
    source: "Sleeper Injury Feed",
    significance: "critical",
  },
  {
    id: "diff-3",
    time: "6 hours ago",
    type: "DEPTH_PROMOTION",
    player: "Brian Thomas Jr. (WR · JAX)",
    metric: "WR1 Snap Share (86%)",
    delta: "+1.9 PPG Projection",
    source: "JAX Depth Chart Delta",
    significance: "medium",
  },
];

export const demoStartSitPairs = [
  {
    id: "ss-1",
    startPlayer: demoPlayers.find((p) => p.id === "p-101")!,
    sitPlayer: demoPlayers.find((p) => p.id === "p-107")!,
    warScoreDelta: "+5.4 pts",
    confidence: 92,
    recommendationReason: "Justin Jefferson maintains a 29.4% target share with an easy #2 secondary matchup.",
    startFloorCeiling: { floor: 14.2, median: 19.8, ceiling: 28.5 },
    sitFloorCeiling: { floor: 9.5, median: 16.4, ceiling: 25.0 },
  },
  {
    id: "ss-2",
    startPlayer: demoPlayers.find((p) => p.id === "p-109")!,
    sitPlayer: demoPlayers.find((p) => p.id === "p-108")!,
    warScoreDelta: "+8.0 pts",
    confidence: 88,
    recommendationReason: "Brian Thomas Jr. boasts 86% snap share vs Samaje Perine's 32% rotational role.",
    startFloorCeiling: { floor: 7.8, median: 14.8, ceiling: 24.2 },
    sitFloorCeiling: { floor: 3.0, median: 6.8, ceiling: 11.5 },
  },
];

export const demoWaiverPairs = [
  {
    id: "w-1",
    addPlayer: demoPlayers.find((p) => p.id === "p-106")!,
    dropPlayer: demoPlayers.find((p) => p.id === "p-108")!,
    faabPercent: "12% - 15%",
    urgency: "HIGH",
    rosOutlook: "Positive (TE1 Upside)",
    warScore: 92,
    reason: "Isaiah Likely offers TE1 target volume; Samaje Perine's touch share is declining.",
    threeWeekOutlook: [
      { week: "Week 2", opponent: "vs LVR", difficulty: "Easy" },
      { week: "Week 3", opponent: "vs DAL", difficulty: "Moderate" },
      { week: "Week 4", opponent: "vs BUF", difficulty: "Favorable" },
    ],
  },
  {
    id: "w-2",
    addPlayer: demoPlayers.find((p) => p.id === "p-109")!,
    dropPlayer: demoPlayers.find((p) => p.id === "p-108")!,
    faabPercent: "18% - 22%",
    urgency: "CRITICAL",
    rosOutlook: "Breakout WR2",
    warScore: 89,
    reason: "Brian Thomas Jr. has secured 86% snaps and high-depth targets.",
    threeWeekOutlook: [
      { week: "Week 2", opponent: "vs CLE", difficulty: "Moderate" },
      { week: "Week 3", opponent: "vs BUF", difficulty: "Favorable" },
      { week: "Week 4", opponent: "vs HOU", difficulty: "Easy" },
    ],
  },
];
